INSERT INTO TASK(ID, USERNAME, DESCRIPTION, COMPLETION_DATE, COMPLETE)
VALUES(1000, 'esha', 'build Spring MVC website', CURRENT_DATE(), false);
INSERT INTO TASK(ID, USERNAME, DESCRIPTION, COMPLETION_DATE, COMPLETE)
VALUES(1001, 'esha', 'type 15 minutes', CURRENT_DATE(), false);
INSERT INTO TASK(ID, USERNAME, DESCRIPTION, COMPLETION_DATE, COMPLETE)
VALUES(1003, 'esha', 'exercise', CURRENT_DATE(), false);